### ISSUE TITLE
Make the carousel responsive

### ISSUE THREAD

**Issue by stephen-golban** [pietile/pietile-carousel#15]
Very lightweight, fast and overall great package, you should consider making it responsive guys. Keep up the great work!!
Also this is the error I get when using the carousel in mobile mode: "_Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted." at usePan.js:22_

**Comment by vshab** [comment]
Hello! Thank you! :)

>you should consider making it responsive

Responsive in what way?

>Also this is the error I get when using the carousel in mobile mode: "Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted." at usePan.js:22

What browser are you using?

**Comment by stef703** [comment]
> Hello! Thank you! :)
> 
> Responsive in what way?
> 
> > Also this is the error I get when using the carousel in mobile mode: "Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted." at usePan.js:22
> 
> What browser are you using?

**Comment by stephen-golban** [comment]
By responsive i meant, to use to on mobile devices too.
I'm using Edge Browser
